### PR TITLE
Several fixes and additions

### PR DESCRIPTION
**Pull request by haavee**
Dear Daniel Price and co-authors,

First of all: THANK YOU SO MUCH for providing an easily compile-able, modern, drop-in replacement for pgplot, supporting more modern systems and outputs!

I work in radio astronomy and developed a visualisation tool built around the python-pgplot binding and users are complaining about how difficult PGPLOT is to build and "can we have PDF output?". In that respect giza is a godsend, making it significantly easier to tell users "just use that in stead".

After compiling + linking the python pgplot binding with giza I discovered a number of small issues, readily fixable. Some less so, e.g. resizing an XWindow behind giza's back. 
In astronomy, time-axis labelling is extremely important. I found this to be not implemented in giza so I took a stab at porting the official PGPLOT "PGTBOX(...)" routine into giza.

Please find a number of commits/patches in this pull request.

I hope the can be deemed useful enough to be considered for inclusion in the official giza distribution.

Let me know if I have missed or overlooked some details - I'd be more than happy to adapt my initial fixes if that would help acceptance!

Thanks again for your work on giza!
cheers,
Harro Verkouter

### CODE REVIEW

**Comment by danieljprice** [comment]
Dear Harro,

 This is absolutely amazing. You’ve pretty much ticked off my entire to-do list for giza. I need to carefully check that this doesn’t break anything (I use giza mainly as a backend for my own visualisation tool) but unless there is anything howlingly wrong I’ll try to merge this in the next couple of days. The only one that worries me is commenting out the call to giza-window in giza-viewport, as I’m sure that was there for a reason, just can’t remember what the reason was…

I would very much welcome any further development, especially since my own contributions to giza have stalled since it is basically stable and satisfies my requirements. However, making giza useful for other projects is extremely worthwhile.

Cheers,

Daniel

**Comment by danieljprice** [comment]
OK, I found a few issues. One of the test suites I use is just the original "pgdemo" programs distributed with the original pgplot. These do not even have to be recompiled to be used with giza, you just have to point to the giza version of pgplot in your LD_LIBRARY_PATH.

This picks up a few problems, the main one being with the giza_band routines. These rely on the X-windows pixel map being buffered rather than being written directly to the window.  Specifically, the issues are:

1) pgdemo1 now seg faults at the end
2) pgdemo2 no longer displays marker symbols correctly on page 2
3) pgdemo5 does not erase the cursor after drawing it
4) pgdemo6 has same issue with giza_band
5) pgdemo9 no longer seems to draw any pattern
6) pgdemo13 has strange behaviour, window is wrong size and seg faults
7) pgdemo14 now just flickers and no longer works

I'll try to poke into some of the above also, there are hopefully simple fixes. I would very much like to merge your changes if we can fix the above issues.

Cheers,

Daniel

**Comment by haavee** [comment]
Hi Daniel,

Well, that's really nice to hear, glad to be of help. Let's see what's going wrong here.

I'd say that reverting the writing back to pixelmap in stead of drawing to the window directly probably fixes many of the issues you report. I mainly did that because I thought it seemed faster. (Which is an issue I intend to look at - it seems that drawing many points is slower than in the original PGPLOT and drawing to the window directly seemed to be faster).

I'll see what I can find locally about these as well.

Cheers,
h

**Comment by danieljprice** [comment]
I've cherry-picked the easy ones onto master to start with, which all seem OK. Now working through the remaining 4 commits. I will try to merge pgtbox next.

also pgdemo9 behaviour is identical on master, so not related to your pull request

**Comment by haavee** [comment]
OK one of these days I should learn how to merge / amend a commit (fixing a small oversight in a previous commit).

But I have added a bunch of new features and fixed a number of bugs

**Comment by danieljprice** [comment]
Hi Harro,

 The resize is now working for me, giza-band seems to work, and the work on character mapping looks great. Remaining issues from what I've tested are:

1) there is a show-stopping bug related to the internal arithmetic on the window size. In my usage it means my interactive zooming does not work properly (i.e. giza reports wrong numbers). I'm trying to track this down.

2) some of the marker sizes seem unusually large. For example in pgdemo1 the circle size is far too big on the plot. I've attached the original pgplot version below for reference.

pgplot_0001

giza-haavee_0000

Aside from those everything looks good as far as I have tested. But both are blocking a merge...

Daniel

**Comment by danieljprice** [comment]
Update: #1 was identical on master, and turned out was not actually a bug, just me interpreting behaviour incorrectly.

#2 is still an issue, but I think it's the only one remaining

**Comment by danieljprice** [comment]
Update: I found issue 2, was just a change you'd seemingly made deliberately in giza-points.c. I've reverted this routine to behaviour on master and will merge everything else.

Thanks again!

**Comment by danieljprice** [comment]
Now merged to master

**Comment by haavee** [comment]
Hi Daniel,

Cool! And: AH! That explains why the marker size was set to .2! Otherwise they'd show up in the plots unusually large! But now they show up in the text as unusually small.

Come to think of it, possibly, in PGPLOT, the marker /size/ actually scales with the character height. I sometimes use it to draw bigger (or smaller) symbols.

So maybe the change should be that the marker size is not a constant fraction of the font's max_x_advance but that size times the current character height? That sounds like it would be natural, the marker size following the user set character height.

That way we both could win ;-)

Cheers,
h

**Comment by haavee** [comment]
There is another thing I'd found and want to discuss.
At some point I started to try using other fonts to see if there was one with more glyphs. So I added some debugging to the _giza_set_font() and found that the FreeType section ("GIZA_HAS_FT_FONT") was not compiled.

So I wondered if my cairo was compiled w/o FreeType support. Turns out it wasn't, so why was the FreeType support not compiled?? Traced this to the "GIZA_HAS_FT_FONT" not always being set correctly.

Long story short - after enabling GIZA_HAS_FT_FONT some things were needed to make the FreeType section work, did that. The FreeType calls as they stand load a font from file on disk. This might come in very useful but does not help if you'd like to load a font installed on your system.

Therefore I added a section dealing with FontConfig patterns to look up fonts using font-config (if cairo was compiled with support for that).

The question is: would it be useful to enhance the \f* font selection mechanism to allow for arbitrary font setting? I was thinking along something like this:
`\f{Monospace}` or `\f{/path/to/font.ttf}` to load your own fonts.

Could be very fancy :-)

Cheers,
h

**Comment by danieljprice** [comment]
Interesting. My understanding was that the max_x_advance should scale with character height (font size), but if it doesn’t then I’m happy to implement something that does.

I’m happy with any suggestions you have here as long as we test it on both plot marker sizes and text rendering.

Cheers,

Daniel

**Comment by danieljprice** [comment]
GIZA_HAS_FT_FONT was just something I was experimenting with, so is off by default. Mainly I was wanting to use a default font like Stix that has full Unicode support so that all mathematical symbols would get plotted in all cases. As it is at the moment, Greek letters show up by default on Mac but not on Linux unless you explicitly set the font to something other than the default (=`Times').

However, enabling freetype gives another dependency to giza so I decided this was not worth it in the end, since the same could be achieved by setting GIZA_FONT=‘Stix’.

I’d support your proposal to add \f{Comic Sans}, just wary about adding dependencies that aren’t really necessary for regular usage.

The cairo docs mention that to get fancy with fonts you shouldn’t rely on cairo alone anymore. They recommend using pango to deal with font selection and text rendering instead.

The other idea I played with was to just process all text with LaTeX. I could figure it out for bitmap formats (i.e. just process text with latex, dvipng, read the file using the cairo png reading routine and overplot it) but wasn’t sure what to do on vector devices like pdf, eps and svg.

In the end I’m happy enough with the simple cairo text + font handling, but it does have deficiencies.

Daniel

**Comment by haavee** [comment]
I interpreted that property as a true property of the font, not how it's rendered on the screen.

This snippet from the `cairo` documentation was my main reason for thinking so:

> Because font metrics are in user-space coordinates, they are mostly, but not entirely, independent of the current transformation matrix. If you call cairo_scale(cr, 2.0, 2.0), text will be drawn twice as big, but the reported text extents will not be doubled. They will change slightly due to hinting (so you can't assume that metrics are independent of the transformation matrix), but otherwise will remain unchanged.

Also from the documentation for `cairo_font_extents()`:

> Gets the font extents for the currently selected font.

Which seems to hint at the fact that the font has its extents and for rendering a transformation matrix is used.

I would simply do a `giza_get_character_height()` inside `_giza_get_markerheight()` and change that multiplication by `0.2` to multiplication by that number.

I see that in `pgdemo2.f` in the FONTS display example (where markers are embedded in the text) a character height of `1.6` is set (`PGSCH(1.6)`)

So maybe scaling the marker height by the character height would make them come out Just Fine.

Cheers,
h

**Comment by haavee** [comment]
In totally other news: got two new things ... one a one line change in the back-space handling code and one which is more serious when I implemented `cpgqinf()` ...
You can check those commits on my github fork and see what you think.

Cheers!
h

**Comment by haavee** [comment]
The Giza freetype font support can follow cairo's capabilities, as in: if
cairo was compiled with freetype then giza could just use it and if cairo
wasn't built with freetype then neither would giza.
This would not introduce any new dependencies because, well, cairo needs to
be there *anyway* :-)

So that's the font I should be trying? It should come from fontconfig
matching. (A similar approach was followed here: if cairo was built with
fontconfig support only then that is used, otherwise that code is not
compiled).

cheers,
h

**Comment by haavee** [comment]
Check! Replaced giza_set_font("Times") with giza_set_font("Stix") and
suddenly many (if not most) math symbols pop up.
See screenshot.
[image: Screen Shot 2018-09-07 at 01.15.30.png]

**Comment by haavee** [comment]
anyway, signing off now - getting late here ;-)

**Comment by danieljprice** [comment]
You can do this at runtime using the environment variable GIZA_FONT

i.e. export GIZA_FONT=‘Stix’

...but on Mac Stix is not installed by default so the cairo fallback gives you something more like Helvetica, whereas I wanted a Times-like font by default. Hence why default is `Times'

**Comment by danieljprice** [comment]
http://www.stixfonts.org

**Comment by haavee** [comment]
Sure, I just wanted to see what that font looked like ;-)
No way going to commit *this* to any repository! I found it hard to figure
out which fonts are actually installed so your font name was a great help!

cheers,
h

**Comment by danieljprice** [comment]
Hi Harro,

 Just for my workflow, would be great if you could issue a fresh pull request for additional features. Gives me a "working deadline" to try to get it merged. Otherwise I won't pull and test things regularly.

We're looking at applying for some software support for giza based ere in Australia, so I'd be interested in any features you think are still missing/not working correctly.

Cheers,

Daniel

**Comment by haavee** [comment]
Hi Daniel,

No prob! I was just being a bit hesitant to start making pull requests ...
to me it still feels a bit, well, pushy, if I create a pull-request, as if
I'm 'forcing' something onto someone. It'll get better ;-)
But that is good news! Can you tell me (a little) bit more about that, e.g.
who is using giza e.g.? Because just this week I got a question from my
supervisor, to the effect of "great that you've put in effort into this
project! by the way who's actually using it?" So it would be great if I can
bring some of this positive news (e.g. applying for software support
because other people think it's valuable) would be greatly appreciated.

I'll be on holiday for a week next week so communication may be laggy. I'll
give some thought to features - although I think that at the moment speed
is at the top of my prio list for this; there's a noticeable speed
difference that I want to look into.

Cheers,
h

**Comment by haavee** [comment]
Hi Peter,

Thanks for that! I did NOT know that, though I have a long, very long,
history with the CASA project (when I started it was still called 'aips++',
if that even means something to you). We use aips++/casa/casacore
internally here on a daily basis. Can you be a little more specific about
where because I never ran into it?

And in fact, my desire for pgplot (and its replacement) come from a
plotting package I wrote for the MeasurementSet data format, you can check
it out here:
    https://github.com/haavee/jiveplot
I found that PGPLOT was (a lot!) faster than matplotlib and also it gave me
a much better control over plot layouts &cet.

Cheers and thanks!
h

**Comment by pkgw** [comment]
[This link](https://github.com/pkgw/casa/search?q=pgplot&unscoped_q=pgplot) searches for pgplot in the CASA repository ... I think it gets used internally for plotting images in things like the interactive CLEAN tool.

(One of my favorite CASA facts is that I was able to speed up the *bandpass plotter* by more than an order of magnitude by using my own plotting tools instead of CASA's built-in support ... the C++ code starts up an internal Python interpreter and feeds data to matplotlib internally!)

**Comment by haavee** [comment]
Thanks - my colleague who's also working a bit of CASA did pretty much the
same, grepping on a local checkout with, unsurprising, pretty much the same
result.

I heard about the internals starting a Python interpreter and feeding
commands to matplotlib from /another/ colleague (who integrated casa with
jupyter notebook - and ran into this gem of plotting :-))

Cheers,
h

**Comment by karlglazebrook** [comment]
This is looking very very nice now.

My own experiments have shown that matplotlib is an order of magnitude slower than pgplot - it is because in matplotlib every graphic element is an object - so when you draw 10,000 of them things can get slow. Giza is similarly fast.

It is great to have a C-based plotting library which is fast and does not require an interpreter.

**Comment by danieljprice** [comment]
I’ll just add a comment here - there is always a trade-off between nice looking plots and speed.

giza is certainly slower than PGPLOT, because it uses antialiased fonts and marker symbols compared to PGPLOT's pixmap splatting. So it depends what you want to achieve.

One of the reasons I adopted cairo was the option to have an openGL backend. I never got around to writing that, but if you wanted very fast X11 plotting, writing an X11-openGL backend would be the way to go, in principle offering fast interactivity with 3D graphics too.

Daniel

**Comment by haavee** [comment]
Hi all,

Speaking of speed ... I have started on an attempt of speeding up pgpt() -
I think I should be able to get an increase when plotting many points (I
would notice that in my application easily enough)
I'll keep you posted; I'm travelling this week but after that I should have
time to work on it.

Cheers,
h

Op zo 21 okt. 2018 om 17:57 schreef Daniel Price <notifications@github.com>

**Comment by karlglazebrook** [comment]
I do think it would be nice to have a pure OpenGL backend, doing away with the need to have a X11 server. Could this be a way to make it work on windows too? I don’t know how we would get that written if you do not have time...

Right now I think the speed is great!

Karl

**Pull request closed without merging**
