### PR TITLE
Fix crashes: multiple simultaneous device was broken, more memory management

### PR DESCRIPTION
**Pull request by haavee**
Hi all (again ...),

Sadly, my interactive plot program crashed continuously using giza as backend. This pull request contains three commits fixing the most severe/reproducible ones. It is a rather big one, unfortunately, hence also a more detailed explanation.

## Open/close bookkeeping and initialization/de-initialization
The main crashing mechanism was traced to `giza_open_device_size()` and `giza_close_device()` not supporting opening/closing multiple devices in arbitrary order - which is what the application does, unfortunately. The giza internal device bookkeeping would break and lead to API calls corrupting memory, leading to SIGSEGV or libc `malloc/free`, detecting their internal structures being corrupted, triggering a force-quit of the application.

In order to do the C memory and `giza_device_t` status management correctly, better bookkeeping, initialization and de-initialization was necessary. Handling of possible error(s) during the open/initialize phase of a device was added.

## `giza_format_number` writing into target string without knowledge of size
Whilst chasing the crashes (big thanks to [@valgrind](http://valgrind.org/)!) found another unbounded write-to-target-string: `cpgnumb()`, `PGNUMB()` - implemented by `giza_format_number()`. `giza_format_number()` now takes an extra argument, the size of the destination string.
The `cpgnumb()` is the dangerous one and could, possibly, usefully be dropped. There is *no way*, without changing the current pgplot C API, documentation and applications who use this API call, to be guaranteed it passes the string buffer's length!
The (updated) FORTRAN binding`giza-pgplot.f90`, PGPLOT's `libcpgplot` binding and @karlglazebrook 's `perl5-PGPLOT` binding all pass a string length into `cpgnumb()`, `PGNUMB()`'s parameter before calling and should be OK. Python's `ppgplot` module does not even bind the `cpgnumb()` function - possibly exactly because of this reason.

## Font handling, caching
With multiple device support, a single, global, variable tracking "what is the current font" is not appropriate. Each `giza_device_t` must keep its current font independently. Font faces are now loaded on first use, cached, shared between devices, and typically only unloaded at program exit. Font faces are cached/looked up by their key properties (family, slant, and weight) and reference counted (with a slight twist to prevent excessive font create/destroy sequences, see `src/giza-set-font.c`) when device(s) change font or are opened/closed. Font loading now automatically follows `cairo's` capabilities it was compiled with (FreeType, FontConfig). Because `cairo` is a necessary dependency anyway (...) this does introduce new ones.

## `splash`
These changes were tested against a few `pgdemo` programs (specifically `pgdemo2` - the fonts) and `splash`, both still seem to work. I did notice that in splash's `build/Makefile` I had to apply this diff snippet:
`-CAIRO_CFLAGS= -I$(X11_DIR)/include`
`+#CAIRO_CFLAGS= -I$(X11_DIR)/include` 
or else `giza/configure` would not even attempt to get the proper include path from `pgk-config --cflags cairo`, resulting in freetype header file(s) not being found, even though `cairo` was built with support for that. `giza/configure`, if it detects `CAIRO_CFLAGS` is set externally, does not run `pkg-config`.

### CODE REVIEW

**Comment by danieljprice** [comment]
also struggles to find freetype and fontconfig libraries by default (even though cairo is built with them):
```
Undefined symbols for architecture x86_64:
  "_FT_Done_Face", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
  "_FT_Init_FreeType", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
  "_FT_New_Face", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
  "_FcInit", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
  "_FcInitLoadConfigAndFonts", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
  "_FcPatternBuild", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
  "_FcPatternDestroy", referenced from:
      __giza_resolve_font in libgiza_la-giza-set-font.o
```

**Comment by danieljprice** [comment]
I have amended the configure script to look for freetype and fontconfig, so I think this is looking OK now

**Comment by danieljprice** [comment]
merged (6a166da), with some additional changes to configure script and Makefile.am

**Comment by haavee** [comment]
Yes, the `ft2build.h` was giving me a headache too ... hail package management ...

If I understand correctly:
- the configure script now always looks for freetype2/fontconfig independently, to test for those libraries on non- or broken `pkg-config` systems, e.g. OSX; the rationale being that on those system(s) `pkg-config --cflags cairo` doesn't actually work
- `giza`'s new `giza-set-font` will only actually _use_ freetype/fontconfig if `cairo` was actually compiled with support for any/all of these - so I think this is indeed a sensible approach
- but only as long as `PKG_CHECK_MODULES([FT]` (and for `[FC]`) failing to find the package(s) is not fatal. That, I do not know.

**Comment by danieljprice** [comment]
First, I found that to fix the build failure I needed the -lfreetype and -lfontconfig explicitly on the command line given they are called directly from giza, so that was the main reason for edits to configure.ac.

On the third point, I’ve confirmed that the fallback options work on Mac OS when pkg-config is not present by default. This is important because basically the only thing you need for giza is to install Xquartz, which comes with cairo, freetype and fontconfig libraries already installed in /usr/X11/, so by default if pkg-config does not find cairo etc. elsewhere (or pkg-config does not exist) then the Xquartz-bundled libraries are found.

For the second point, I haven’t checked what actually happens if freetype/fontconfig are not present. This seems unlikely given cairo usually requires them, but then again I did find a problem recently where a user did not get the X-windows driver in giza because pkg-config found a cairo bundled with anaconda that did not have the X-win driver installed (hence giza happily compiled, but without an /xw driver).

**Pull request merged**
